# Generated by Django 3.2.7 on 2021-12-29 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx', models.CharField(max_length=8192, verbose_name='transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=60, verbose_name='productId')),
                ('product_name', models.CharField(max_length=120, verbose_name='productName')),
                ('category', models.CharField(max_length=120, verbose_name='category')),
                ('price', models.IntegerField(verbose_name='price')),
                ('description', models.CharField(max_length=240, verbose_name='description')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.contracttransaction')),
            ],
        ),
    ]
