# Generated by Django 3.2.7 on 2022-01-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=60, verbose_name='productId')),
                ('product_name', models.CharField(max_length=120, verbose_name='productName')),
                ('category', models.CharField(max_length=120, verbose_name='category')),
                ('price', models.IntegerField(verbose_name='price')),
                ('description', models.CharField(max_length=240, verbose_name='description')),
                ('transaction', models.CharField(max_length=8192)),
            ],
        ),
    ]
