# Generated by Django 3.2.7 on 2021-12-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=128)),
                ('_from', models.CharField(max_length=128, verbose_name='from')),
                ('price', models.IntegerField(verbose_name='price')),
                ('private_key', models.CharField(max_length=256, verbose_name='description')),
                ('transaction', models.CharField(max_length=8192, verbose_name='transaction')),
            ],
        ),
    ]
