# Generated by Django 3.2.7 on 2021-12-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='_from',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='private_key',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction',
            field=models.CharField(max_length=8192),
        ),
    ]
